name: CI

on:
    push:
        branches: [ main , homework-* ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
    # Hacky hack to use a variable afterwards, see also
    # https://github.community/t/how-to-use-env-with-container-image/17252/24
    set_env:
        runs-on: ubuntu-latest
        outputs:
            REGISTRY : ${{steps.save_var.outputs.REGISTRY}}
        steps:
            - id: save_var
              run: |
                echo "::set-output name=REGISTRY::${{ env.REGISTRY }}"

    build-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Docker registry login
              run : |
                  docker login -u ${{ github.actor}} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            - name: Docker image pull (try)
              run : |
                  docker pull ${{ env.REGISTRY }}/${{ github.repository }}
            - name: Docker image build
              run : |
                  docker build \
                      -f dockerfile \
                      --cache-from ${{ env.REGISTRY }}/${{ github.repository }} \
                      -t ${{ env.REGISTRY }}/${{ github.repository }} \
                      .
            - name: Docker image push
              run : |
                  docker push ${{ env.REGISTRY }}/${{ github.repository }}

    homework-1:
        runs-on: ubuntu-latest
        needs: [set_env,build-image]
        container:
            image: ${{ needs.set_env.outputs.REGISTRY }}/${{ github.repository }}
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - name: Check .geo files are valid by meshing them
              run : |
                  gmsh -2 homework-1/busbar.geo
                  gmsh -2 homework-1/busbar.sym.geo
            - name: Run simulations with the default parameters to check they are valid
              run : |
                  getdp homework-1/busbar.pro -solve EleKin_v -pos Map
                  getdp homework-1/busbar.sym.pro -solve EleKin_v -pos Map
            - name: Check optimization
              run : |
                  pytest homework-1/ -s --log-cli-level=info
            - name: Compile report
              run : |
                  bash compile.latex.sh homework-1/report/report-hw-1.tex
            - name: Uploading artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: homework-1
                  retention-days: 5
                  path: |
                      report-hw-1.pdf
                      homework-1/*.pro
                      homework-1/*.geo
                      optimization.py
                      test_mesh_convergence.py
                      test_optimization.py
